SECRET_KEY = 'your-secret'

SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite'
OAUTH_CACHE_DIR = '_cache'

GOOGLE_CLIENT_KEY = '861011153873-8a1akes1g91ht64l699r58onforrjfgi.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = 'MdQwMuwxHLtt2pEGA5UJrtUl'

TWITTER_CLIENT_KEY = ''
TWITTER_CLIENT_SECRET = ''

GITHUB_CLIENT_KEY = ''
GITHUB_CLIENT_SECRET = ''

FACEBOOK_CLIENT_KEY = ''
FACEBOOK_CLIENT_SECRET = ''
